int	nombre,tipo,*a,edad,nombreDueño;	
cout<<"Bienvenido a la veterinaria Maria Luz"<<endl;
cout<<"Ingresa primero que tipo de animal es tu mascota: "<<endl;
cin<<tipo;
*a=tipo;
cout<<"Ahora dinos el nombre: "<<endl;
cin<<nombre;
cout<<"Que edad tiene tu mascota? : "<<endl;
cin<<edad;
cout<<"Por ultimo cual es el nombre del dueño?: "<<endl;
cin<<nombreDueño;